/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oktaviana larasati
 */
public class TugasBaruBismillah extends javax.swing.JFrame {

    /**
     * Creates new form TugasBaruBismillah
     */
    public TugasBaruBismillah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFungsi = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        nilaiA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nilaiX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nilaiN = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Aproksimasi F(X)");

        jLabel2.setText("PILIH JENIS FUNGSI :");

        jFungsi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "f(x)=sin(2x)", "f(x)=cosh(-6x)", "f(x)=x/(1-x)", " ", " " }));
        jFungsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFungsiActionPerformed(evt);
            }
        });

        jLabel3.setText("Masukkan Nilai A");

        jLabel4.setText("Masukkan Nilai X");

        jLabel5.setText("Masukkan Nilai N");

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        Reset.setText("Reset");

        jLabel6.setText("Hasil :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Hitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Reset))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(nilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(nilaiX, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(nilaiN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addGap(15, 15, 15))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jFungsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(171, 171, 171)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFungsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nilaiX, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nilaiN))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hitung)
                    .addComponent(Reset))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Hasil, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFungsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFungsiActionPerformed
        
        String soal = (String)jFungsi.getSelectedItem();
        if (soal == "no2"){
             String no2 = "f(x)= sin(2x)";
        TampilanSoal.setText(String.valueOf(no2));
   } else if(soal=="no3"){
       String no3 = " f(x) = cosh (-6) ";
       TampilanSoal.setText(String.valueOf(no3));         
   } else if(soal=="no5"){
       String no5 = "f(x) = x/(1-x) ";
       TampilanSoal.setText(String.valueOf(no5));
   }
       
    }//GEN-LAST:event_jFungsiActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        double a = Double.parseDouble(nilaiA.getText());
        double x = Double.parseDouble(nilaiX.getText());
        double n = Double.parseDouble(nilaiN.getText());
       double es = 0.5*Math.pow(10, (2-n));
       double[] f= new double[1000001];
       double error= 0;
       switch(jFungsi.getSelectedIndex()){
           case 1:
               f[0] = Math.sin(Math.toRadians(2*a))+Math.cos(Math.toRadians(2*a)) * (Math.toRadians(x-a));
               
               for(int i =1 ; i<=100000; i++){
                   f[i] = f[i-1] + ((Math.pow(-1, i) * Math.sin(Math.toRadians(2*i))
                           * Math.pow(Math.toRadians(x-a), 2*i))/ faktorial (2*i))+Math.pow(-1,i)
                           *Math.pow(2,(2*i+1)*Math.cos(Math.toRadians(2*a))
                           *Math.pow(Math.toRadians(x-a),2*i+1)/faktorial(2*i));
                   
                   double ea = ((f[i] - f[i-1])/f[i])*100;
                   if(Math.abs(ea)<es){
                       error += f[i];
                       break;
                   }
                           }
           Hitung.setText(String.valueOf(error));
               break;
               
           case 2 :
           f[0]=((Math.exp(6*a))+(Math.exp((-6)*a)))/2;
           for (int i=1;i<= 1000000; i++){
               if(a==0){
                   f[i]= f[i-1] + ((Math.pow(6*x,2*i))/faktorial(2*i));
               }else{
                   f[i]=f[i-1] + ((Math.exp(6*a)+Math.pow((-1),i)*(Math.exp(-6*a))
                           *(Math.pow(6,i)*Math.pow(x-a, i))))/(2*(faktorial(i)));
                   
               }
               double ea = ((f[i]-f[i-1])/f[i])*100;
               if(Math.abs(ea)<es){
                  error += f[i];
                  break;
               }
           }
           Hitung.setText(String.valueOf(error));
               break;
               
           case 3 :
               f[0]=a/(1-a);
               for(int i=1; i<1000000;i++){
               f[i]=f[i-1]+deret(a, a, i);
               double ea = ((f[i]-f[i-1])/f[i])*100;
               if(Math.abs(ea)<es){
                   error += f[i];
                   break;
               }
               }
       }
                
    }//GEN-LAST:event_HitungActionPerformed
public static double faktorial(int bilangan){
    if(bilangan==1 || bilangan==0){
        return 1;
    }else{
        return bilangan * faktorial(bilangan-1);
    }
}

    public static double deret(double x, double a , int suku){
    double hasil = (1/(1-a));
    for(int i=1; i<=suku; i++){
        hasil *= (x-a)/(1-a);
    }return hasil;
}

//Penyelesaian No 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasBaruBismillah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasBaruBismillah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasBaruBismillah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasBaruBismillah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasBaruBismillah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hasil;
    private javax.swing.JButton Hitung;
    private javax.swing.JButton Reset;
    private javax.swing.JComboBox jFungsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nilaiA;
    private javax.swing.JTextField nilaiN;
    private javax.swing.JTextField nilaiX;
    // End of variables declaration//GEN-END:variables
}
