/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oktaviana larasati
 */
public class Oktaviana_tugas2 extends javax.swing.JFrame {

    /**
     * Creates new form Oktaviana_tugas2
     */
    public Oktaviana_tugas2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fungsi = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nilaiA = new javax.swing.JTextField();
        nilaiX = new javax.swing.JTextField();
        nilaiN = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        fungsiterpilih = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setText("APROKSIMASI F(X)");

        jLabel2.setText("PILIH JENIS FUNGSI :");

        fungsi.setBackground(new java.awt.Color(204, 204, 255));
        fungsi.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        fungsi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "f(x) = sin 2x", "f(x) = cosh(-6x)", "f(x) = x/(1-x)", " " }));
        fungsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fungsiActionPerformed(evt);
            }
        });

        jLabel3.setText("Masukkan Nilai a");

        jLabel4.setText("Masukkan Nilai x");

        jLabel5.setText("Masukkan Nilai n");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel6.setText("Hasil =");

        hasil.setText("");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });

        fungsiterpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fungsiterpilihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(nilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fungsiterpilih)
                            .addComponent(fungsi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nilaiX, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(nilaiN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reset)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fungsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fungsiterpilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nilaiA, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(nilaiX)
                    .addComponent(nilaiN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitung)
                    .addComponent(reset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fungsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fungsiActionPerformed
        // 
        switch (fungsi.getSelectedIndex()){
            case 1 : //soal no 2
                nilaiA.setText(null);
                nilaiX.setText(null);
                nilaiN.setText(null);
                hasil.setText(null);
                fungsiterpilih.setText("f(x)=sin 2x");
                break;
                
            case 2 : //soa; no 3
                nilaiA.setText(null);
                nilaiX.setText(null);
                nilaiN.setText(null);
                hasil.setText(null);
                fungsiterpilih.setText("f(x)=cosh (-6x)");
                break;
                
            case 3 : //soal no 5
                nilaiA.setText(null);
                nilaiX.setText(null);
                nilaiN.setText(null);
                hasil.setText(null);
                fungsiterpilih.setText("f(x)= x/(1-x)");
                break;
                
            default : 
                nilaiA.setText(null);
                nilaiX.setText(null);
                nilaiN.setText(null);
                hasil.setText(null);
                fungsiterpilih.setText(null);
                break;
                
                
            
        }
    }//GEN-LAST:event_fungsiActionPerformed

    public static double faktorial (int bilangan){
      int faktor =1;
      for (int s = 1; s<=bilangan; s++){
          faktor = faktor*s;
      }
      return faktor;
    }
    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(nilaiA.getText());
        double x = Double.parseDouble(nilaiX.getText());
        double n = Double.parseDouble(nilaiN.getText());
        double es = 0.5*Math.pow(10, (2-n));
        double[] f= new double[1001];
        double function = 0;
        switch( fungsi.getSelectedIndex()){
            case 1 :
                f[0] = (Math.sin(Math.toRadians(2*a))+Math.cos(Math.toRadians(2*a))) * (Math.toRadians(x-a));
              for(int i=1; i<=1000 ; i++){
                f[i] = f[i-1]+((Math.pow(-1, i) * Math.sin(Math.toRadians(2*i))  
                        *Math.pow(Math.toRadians(x-a), 2*i))/faktorial(2*i)) + Math.pow(-1,i)
                        *Math.pow(2,(2*i+1)*Math.cos(Math.toRadians(2*a))
                        *Math.pow(Math.toRadians(x-a), 2*i+1)/faktorial(2*i+1));
                
                double ea = ((f[i] -f[i-1])/f[i])*100;
                if(Math.abs(ea)<es){
                    function += f[i];
                    break;
                }
          
            }
             double jawaban2= Math.floor(function*1000)/1000;
             hasil.setText(String.valueOf(jawaban2));
         break;
            case 2:
                f[0] = (Math.exp(6*a)+Math.exp(-6*a))/2;
                for (int i=1;1<=1000; i++){
                    if(a==0){
                        f[i]=f[i-1]+Math.pow(6*x,2*i)/faktorial(2*i);
                    }else{
                        f[i]= f[i-1]+((Math.exp(6*a)+Math.pow(-1,i)*Math.exp(-6*a))
                                *(Math.pow(6, i)*Math.pow(x-a, i)))/(2*(faktorial(i)));
                    }
                    double ea = ((f[i]-f[i-1])/f[i])*100;
                    if(Math.abs(ea)<es){
                        function +=f[i];
                        break;
                        
                    }
                }
           double jawaban3 = Math.floor(function*1000)/1000 ;
           hasil.setText(String.valueOf(jawaban3));
           
                
                break;
                
            case 3:
                f[0]=a/(1-a);
                for(int i=1; i<1000; i++){
                    f[i]= f[i-1]+deret (x,a, i);
                    double ea = ((f[i]-f[i-1])/f[i])*100;
                    if(Math.abs(ea)<es){
                        function += f[i];
                        break;
                    
                    }
                   
                    
                }
            double jawaban5 = Math.floor(function*1000)/1000;
                hasil.setText(String.valueOf(jawaban5));
                break;
           
        }
   
        
    }//GEN-LAST:event_hitungActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

// TODO add your handling code here:
        nilaiA.setText(null);
        nilaiX.setText(null);
        nilaiN.setText(null);
        hasil.setText(null);
        
    }//GEN-LAST:event_resetActionPerformed

    private void fungsiterpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fungsiterpilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fungsiterpilihActionPerformed
public static double deret (double x, double a, int U){
    double hasil = ( 1/(1-a));
    for(int i=1; i<=U; i++){
    hasil *=(x-a)/(1-a);
    } return hasil; 
    
    
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oktaviana_tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oktaviana_tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oktaviana_tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oktaviana_tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oktaviana_tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fungsi;
    private javax.swing.JTextField fungsiterpilih;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nilaiA;
    private javax.swing.JTextField nilaiN;
    private javax.swing.JTextField nilaiX;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
